pom.groupId=org.jraf
pom.version=2.0.0
pom.description=A Notion API client library for Kotlin, Java and more.
pom.vcsUrl=https://github.com/BoD/klibnotion
pom.developer=Benoit \'BoD\' Lubek
pom.license=Apache-2.0
java.compatibility=17
kotlin.compatibility=2.3.0
kdoc.projects=:klibnotion
