{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibnotion/2.0.1-SNAPSHOT/klibnotion-2.0.1-SNAPSHOT.module",
    "group": "org.jraf",
    "module": "klibnotion",
    "version": "2.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnotion-jvm-2.0.1-SNAPSHOT.jar",
          "url": "klibnotion-jvm-2.0.1-SNAPSHOT.jar",
          "size": 1345886,
          "sha512": "0f0e4683a462e5df8f53db78f0753372659983bc5b8ce401a8cb9e98018ce5bc75d8860c2081dbf39f20b786c188ac5ae0d9ba1ac771491a0db16c713c271083",
          "sha256": "82b832ca4a8bdc673b2e6477b54ab632389574a8a67546afc44b5adae2c10a0f",
          "sha1": "60d811fd3bf9b3f3c74cc020e5a51ace8eec7eed",
          "md5": "d8190cef7498117b51283d2341ea4ad6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibnotion-jvm-2.0.1-SNAPSHOT.jar",
          "url": "klibnotion-jvm-2.0.1-SNAPSHOT.jar",
          "size": 1345886,
          "sha512": "0f0e4683a462e5df8f53db78f0753372659983bc5b8ce401a8cb9e98018ce5bc75d8860c2081dbf39f20b786c188ac5ae0d9ba1ac771491a0db16c713c271083",
          "sha256": "82b832ca4a8bdc673b2e6477b54ab632389574a8a67546afc44b5adae2c10a0f",
          "sha1": "60d811fd3bf9b3f3c74cc020e5a51ace8eec7eed",
          "md5": "d8190cef7498117b51283d2341ea4ad6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibnotion-jvm-2.0.1-SNAPSHOT-sources.jar",
          "url": "klibnotion-jvm-2.0.1-SNAPSHOT-sources.jar",
          "size": 343340,
          "sha512": "89d3c80be2b57e804d5f99552c41fadd8a90696fbc04f56cb32f32f8a57e9c90b003a244b093909a7400edd15a2c11dd2ce7e9ab584f412c2f5307cc99dd6ea6",
          "sha256": "faa8317c506798c34d302b22453128c2b1154c7314c61eab299ab3cd453ca333",
          "sha1": "931dff419a19b49945f6878458bd7fb372362d53",
          "md5": "4f7f0c65d7cfcf84cae8370fd265a3f3"
        }
      ]
    }
  ]
}
